### ISSUE TITLE
Undefined method 'feature'

### ISSUE THREAD

**Issue by nstoker** [nstoker/RubyOnRailsWindowsWoes#1]
The first hurdle. 

This occurred once the initial project was build using the rails composer.

```
C:/Users/user/Development/rails/RubyOnRailsWindowsWoes/spec/features/users/sign_in_spec.rb:5:in `<top (required)>': undefined method `feature' for main:Object (NoMethodError)
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.2.0/bin/rspec:23:in `load'
        from C:/RailsInstaller/Ruby2.2.0/bin/rspec:23:in `<main>'
```

**Comment by nstoker** [comment]
The fix for this was to add
`require 'capybara/rspec'` 
to [spec/spec_helper.rb](https://github.com/nstoker/RubyOnRailsWindowsWoes/blob/feature/Issue_1/spec/spec_helper.rb), as shown in [feature/Issue_1](https://github.com/nstoker/RubyOnRailsWindowsWoes/tree/feature/Issue_1)
