### ISSUE TITLE
Uninitialised constant Warden (NameError)

### ISSUE THREAD

**Issue by nstoker** [nstoker/RubyOnRailsWindowsWoes#2]
The next issue - this one stumped me in the 'real' project I was trying to work on, hence the creation of this project.

```
C:/Users/user/Development/rails/RubyOnRailsWindowsWoes/spec/features/users/user_delete_spec.rb:1:in `<top (required)>': uninitialized constant Warden (NameError)
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.2.0/bin/rspec:23:in `load'
        from C:/RailsInstaller/Ruby2.2.0/bin/rspec:23:in `<main>'
```

**Comment by nstoker** [comment]
The current testing branch is [feature/Issue_2](https://github.com/nstoker/RubyOnRailsWindowsWoes/tree/feature/Issue_2)
